# clang 的 MinGW GNU driver 在部分 Linux 发行版上会默认寻找不匹配的 GCC runtime。
# 该规则文件只用于排查链接器差异；正常 clang64 构建使用 lld、libc++ 和 compiler-rt。
if(NOT DEFINED MINGW_TOOLCHAIN_PREFIX OR MINGW_TOOLCHAIN_PREFIX STREQUAL "")
  set(MINGW_TOOLCHAIN_PREFIX "x86_64-w64-mingw32")
endif()

set(CMAKE_C_LINK_EXECUTABLE
    "${MINGW_TOOLCHAIN_PREFIX}-gcc <CMAKE_C_LINK_FLAGS> <LINK_FLAGS> <OBJECTS> -o <TARGET> <LINK_LIBRARIES>"
)
set(CMAKE_CXX_LINK_EXECUTABLE
    "${MINGW_TOOLCHAIN_PREFIX}-g++ <CMAKE_CXX_LINK_FLAGS> <LINK_FLAGS> <OBJECTS> -o <TARGET> <LINK_LIBRARIES>"
)
